WebPF/webpf/admin/auth.py
from flask import (
    redirect,
    request,
    url_for,
)
from flask.ext import (
    admin,
    login,
)
from drake.data.user.forms import LoginForm


def current_user_is_admin():
    user = login.current_user
    return user is not None and \
           user.is_authenticated() and \
           user.is_admin


class AuthenticatedMixin(object):
    def is_accessible(self):
        return current_user_is_admin()


class AdminLoginForm(LoginForm):
    def validate(self):
        preliminary_validation = super(AdminLoginForm, self).validate()
        if not preliminary_validation:
            return False
        if not self.user.is_admin:
            self.username.errors.append("User not authorized")
            return False
        return True


class AuthenticatedAdminIndexView(admin.AdminIndexView):

    @admin.expose('/')
    def index(self):
        if not current_user_is_admin():
            return redirect(url_for('.login'))
        return super(AuthenticatedAdminIndexView, self).index()

    @admin.expose('/login', methods=('GET', 'POST'))
    def login(self):
        # handle user login
        form = AdminLoginForm(request.form)
        if admin.helpers.validate_form_on_submit(form):
            login.login_user(form.user, remember=form.remember)

        if current_user_is_admin():
            return redirect(url_for('.index'))

        self._template_args['form'] = form
        self._template_args['link'] = 'Administrator Login'

        render_index = super(AuthenticatedAdminIndexView, self).index
        return render_index()

    @admin.expose('/logout')
    def logout(self):
        login.logout_user()
        return redirect(url_for('.index'))

WebPF/webpf/app.py
# -*- coding: utf-8 -*-
'''The app module, containing the app factory function.'''

from __future__ import absolute_import

from flask import Flask, render_template

from featuredb.compat import string_types
from featuredb.app import register_extensions as register_featuredb_extensions


from webpf import settings

from webpf.extensions import (
    cache,
    bcrypt,
    login_manager,
    admin,
    celery,
)
from webpf.assets import assets
from webpf import views

_DEFAULT_NAME = __name__


def create_app(package_name=_DEFAULT_NAME,
               settings_object=settings.Production,
               settings_override=None):
    '''An application factory, as explained here:
        http://flask.pocoo.org/docs/patterns/appfactories/

    :param config_object: The configuration object to use.
    '''

    if isinstance(settings_object, string_types):
        settings_object = getattr(settings, settings_object.lower().capitalize())

    app = Flask(package_name, )
    app.config.from_object(settings_object)
    app.config.from_pyfile(app.config.get('WEBPF_LOCAL_CONFIG_PATH', None), silent=True)
    app.config.from_envvar(app.config.get('WEBPF_LOCAL_CONFIG_VAR', ''), silent=True)
    app.config.update(settings_override)

    register_extensions(app)
    register_blueprints(app)
    register_errorhandlers(app)

    return app


def register_extensions(app):
    assets.init_app(app)
    cache.init_app(app)
    bcrypt.init_app(app)
    login_manager.init_app(app)
    celery.init_app(app)
    register_featuredb_extensions(app)
    admin.init_app(app)


def register_blueprints(app):
    app.register_blueprint(views.public.blueprint)
    app.register_blueprint(views.users.blueprint)


def register_errorhandlers(app):
    def render_error(error):
        # If a HTTPException, pull the `code` attribute; default to 500
        error_code = getattr(error, 'code', 500)
        return render_template("{0}.html".format(error_code)), error_code
    for errcode in [401, 404, 500]:
        app.errorhandler(errcode)(render_error)

WebPF/webpf/extensions/__init__.py
# -*- coding: utf-8 -*-
"""Extensions module. Each extension is initialized in the app factory located
in app.py
"""

__author__ = 'Teague Sterling'

from flask.ext.admin import Admin
from flask.ext.bcrypt import Bcrypt
from flask.ext.cache import Cache
from flask.ext.debugtoolbar import DebugToolbarExtension
from flask.ext.login import LoginManager
from flask.ext.migrate import Migrate

from .celery import (
    Celery,
    RequestContextMixin,
)
from .initbroadcast import InitBroadcaster
from .sqla import (
    PluggableSQLAlchemy as SQLAlchemy,
    Query,
    Model,
    Session,
)

from featuredb.admin.auth import AuthenticatedAdminIndexView

admin = Admin(name='FEATUREdb Administration',
              index_view=AuthenticatedAdminIndexView())
bcrypt = Bcrypt()
celery = Celery(task_mixin_cls=RequestContextMixin)
login_manager = LoginManager()
db = SQLAlchemy(query_cls=Query,
                model_cls=Model,
                session_cls=Session)
migrate = Migrate()
cache = Cache()
debug_toolbar = DebugToolbarExtension()

initboradcaster = InitBroadcaster(['featuredb.data'])

WebPF/webpf/views/__init__.py
from . import public
from . import users

WebPF/webpf/views/helpers.py
# -*- coding: utf-8 -*-
'''Helper utilities and decorators.'''
import base64
from cStringIO import StringIO

from flask import flash

BASE64_URL_ALTCHARS = '-_'
BASE64_DATA_URL_TPL = 'data:{mimetype};base64,{data}'


def to_base64(decoded, altchars='+/', translation=None, clean=True):
    encoded = base64.b64encode(decoded, altchars=altchars)
    if translation is not None:
        encoded = encoded.translate(translation)
    if clean:
        encoded = encoded.strip().replace('\n', '')
    return encoded


def from_base64(encoded, altchars='+/', translation=None):
    if translation is not None:
        decoded = encoded.translate(translation)
    decoded = base64.b64decode(decoded, altchars=altchars)
    return decoded


def image_to_buffer(img, format='PNG'):
    buf = StringIO()
    img.save(buf, format.upper())
    buf.seek(0)
    return buf


def image_to_data(img, format='PNG', mimetype=None):
    if mimetype is None:
        mimetype = "image/{}".format(format.lower())
    buf = image_to_buffer(img, format)
    encoded = to_base64(buf.getvalue(), clean=True)
    data = BASE64_DATA_URL_TPL.format(mimetype=mimetype, data=encoded)
    return data


def flash_errors(form, category="warning"):
    '''Flash all errors for a form.'''
    for field, errors in form.errors.items():
        for error in errors:
            flash("{0} - {1}".format(getattr(form, field).label.text, error), category)

WebPF/webpf/views/public.py
# -*- coding: utf-8 -*-
'''Public section, including homepage and signup.'''
from flask import (
    Blueprint,
    flash,
    redirect,
    request,
    render_template,
    url_for,
)


blueprint = Blueprint('public', __name__, static_folder="../static")


@blueprint.route("/about/")
def about():
    return render_template("public/about.html")

WebPF/webpf/views/users.py
# -*- coding: utf-8 -*-

from flask import (
    Blueprint,
    flash,
    redirect,
    render_template,
    request,
    url_for,
)
from flask.ext import login

from drake.data.user import (
    actions,
    forms,
)
from .helpers import flash_errors


blueprint = Blueprint("user", __name__, url_prefix='/users', static_folder="../static")


@blueprint.route('/register', methods=('GET', 'POST'))
def register_user():
    form = forms.RegisterForm(request.form, csrf_enabled=True)
    if form.validate_on_submit():
        user = actions.create_user(username=form.username.data,
                                   email=form.email.data,
                                   password=form.password.data,
                                   first_name=form.first_name.data,
                                   last_name=form.last_name.data)
        if user.active:
            message = "Your account has been activated. You may no login in."
        else:
            message ="Your account as been created. Please check your email to confirm your registration"
        flash(message, 'success')
        return redirect(url_for('public.home'))
    else:
        flash_errors(form)
    return render_template('users/register.html', form=form)


@blueprint.route('/login', methods=('GET', 'POST'))
def login_user():
    form = forms.LoginForm(request.form, csrf_enabled=True)
    if request.method == 'POST':
        if form.validate_on_submit():
            user = form.user
            remember = form.remember
            next_url = request.args.get('next') or url_for('.')
            actions.login_user(user=user, remember=remember)
            flash("Successfully logged in as {username}".format(username=user.username), 'success')
            return redirect(next_url)
        else:
            flash_errors(form)
    return render_template('users/login.html', login_form=form)


@blueprint.route('/logout')
@login.login_required
def logout_user():
    actions.logout_user()

WebPF/webpf/templates/401.html
{% extends "layout.html" %}

{% block page_title %}Unauthorized{% endblock %}

{% block content %}
<div class="jumbotron">
    <div class="text-center">
        <h1>401</h1>
        <p>You are not authorized to see this page. Please <a href="{{ url_for('public.home')}}">log in</a> or
            <a href="{{ url_for('public.register') }}">create a new account</a>.
        </p>
    </div>
</div>
{% endblock %}

WebPF/webpf/templates/footer.html
<footer>
  <small>
  <ul class="company">
    <li>© Teague Sterling</li>
  </ul>

    <ul class="footer-nav">

      <li><a href="{{ url_for('public.about') }}">About</a></li>

      <li><a href="mailto:teague@blur.compbio.ucsf.edu">Contact</a></li>
    </ul>
  </small>
</footer>

WebPF/webpf/templates/layout.html
<!doctype html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8">

  <title>{% block page_title %}
  
    ZINC
  
    {% endblock %}
  </title>
  <meta name="description" content="{% block meta_description %}{% endblock %}">
  <meta name="author" content="{% block meta_author %}{% endblock %}">

  <!-- Mobile viewport optimized: h5bp.com/viewport -->
  <meta name="viewport" content="width=device-width">

  <link rel="stylesheet" href="{{ url_for('static', filename='libs/font-awesome4/css/font-awesome.min.css') }}">
  {% assets "css_all" %}
    <link rel="stylesheet" href="{{ ASSET_URL }}">
  {% endassets %}

  {% block css %}{% endblock %}

</head>
<body class="{% block body_class %}{% endblock %}">
{% block body %}
{% with form=form  %}
{% include "nav.html" %}
{% endwith %}

<header>{% block header %}{% endblock %}</header>
<div class="{% block content_class %}container{% endblock content_class %}">

  <div role="main">
    {% with messages = get_flashed_messages(with_categories=true) %}
    {% if messages %}
    <div class="row">
      <div class="col-md-12">
        {% for category, message in messages %}
        <div class="alert alert-{{ category }}">
          <a class="close" title="Close" href="#" data-dismiss="alert">&times;</a>
         {{message}}
        </div><!-- end .alert -->
        {% endfor %}
      </div><!-- end col-md -->
    </div><!-- end row -->
        {% endif %}
    {% endwith %}

    {% block content %}{% endblock %}
  </div>

</div><!-- end container -->

{% include "footer.html" %}

<!-- JavaScript at the bottom for fast page loading -->
{% assets "js_all" %}
    <script type="text/javascript" src="{{ ASSET_URL }}"></script>
{% endassets %}
{% block js %}{% endblock %}
<!-- end scripts -->
{% endblock %}
</body>
</html>

WebPF/webpf/templates/nav.html
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">

  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="{{ url_for('public.home') }}">

      ZINC

    </a>
  </div>
  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav">
      <li><a href="{{ url_for('public.home') }}">Home</a></li>
      <li><a href="{{ url_for('public.about') }}">About</a></li>
    </ul>
    {% if current_user and current_user.is_authenticated() %}
    <ul class="nav navbar-nav navbar-right">
        <li>
            <p class="navbar-text"><a class="navbar-link" href="{{ url_for('user.members') }}">Logged in as {{ current_user.username }}</a></p>
        </li>
        <li><a class="navbar-link" href="{{ url_for('public.logout') }}"><i class="fa fa-sign-out"></i></a></li>

    </ul>
    {% elif form %}
    <ul class="nav navbar-nav navbar-right">
      <li><a href="{{ url_for('public.register') }}">Create account</a></li>
    </ul>
    <form id="loginForm" method="POST" class="navbar-form form-inline navbar-right" action="/" role="login">
      {{ form.hidden_tag() }}
      <div class="form-group">
        {{ form.username(placeholder="Username", class_="form-control") }}
        {{ form.password(placeholder="Password", class_="form-control") }}
      </div>
      <button type="submit" class="btn btn-default">Log in</button>
    </form>
    {% endif %}
  </div><!-- /.navbar-collapse -->
  </div><!-- /.container -->
</nav>

WebPF/webpf/templates/users/members.html
{% extends "layout.html" %}
{% block content %}
    <h1>Welcome {{ session.username }}</h1>
    <h3>This is the members-only page.</h3>
{% endblock %}